---
name: actionlint
on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
jobs:
  status-check:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: suzuki-shunsuke/actionlint-action@66efc7d429734a9843e4f31ab23a19a2d6f67c12 # v0.0.3
